language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/
    - node_modules
rvm:
- 2.6.3
before_install:
  - gem install bundler:1.17.3
  - yarn
script: "bundle exec jekyll build"
