language: ruby
dist: xenial
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
    - node_modules
  yarn: true
rvm:
- 2.6.3
before_install:
  - gem install bundler:1.17.3
install:
  - bundle install --jobs 3 --retry 3
  - yarn
script: 
  - bundle exec jekyll build
