language: ruby
dist: xenial
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - gem install bundler:1.17.3
install:
  - bundle install --jobs 3 --retry 3
  - yarn
script: 
  - bundle exec jekyll build
