title: Filmhub
description: Film distribution market network for indie filmmakers and video streaming services
url: https://filmhub.com
permalink: none
plugins:
  # - octopress-autoprefixer
  # - jekyll-sitemap
  # - jekyll-github-metadata
  - jekyll-seo-tag
kramdown:
  parse_block_html: true
sass:
  # style: compressed
  # sourcemap: inline
  # line_numbers: true
  # line_comments: true
  load_paths:
    - _sass
    - node_modules
include:
  - node_modules/jquery/jquery.js
  - node_modules/bootstrap/dist/js/bootstrap.bundle.js
  - node_modules/bootstrap/dist/js/bootstrap.bundle.js.map
  - node_modules/lazyload/lazyload.js
kramdown:
  auto_ids: true
  parse_block_html: true

# jekyll-seo-tag properties
twitter:
  username: filmhubhq
facebook:
  app_id: 159020761463817
  publisher: https://www.facebook.com/filmhubhq
  admins: 1034572123
logo: /images/icon_v2_600.png
social:
  name: Filmhub
  links:
    - https://blog.filmhub.com
    - https://twitter.com/filmhubhq
    - https://facebook.com/filmhubhq
    - https://www.youtube.com/user/kinonationfilms
    - https://www.linkedin.com/company/filmhub/
    - https://instagram.com/filmhubhq
author:
  twitter: filmhubhq
phone: +1-424-209-8578

defaults:
  -
    scope:
      path: oldblog
    values:
      sitemap: false
  -
    scope:
      path: modals
    values:
      sitemap: false
  -
    scope:
      path: help
    values:
      sitemap: false
