title: Filmhub
description: Film distribution platform for indie filmmakers and video streaming services
url: https://filmhub.com
permalink: none
sass:
  # style: compressed
  # sourcemap: inline
  # line_numbers: true
  # line_comments: true
  load_paths:
    # - _sass
    - node_modules
include:
  - node_modules/jquery/dist/jquery.min.js
  - node_modules/jquery/dist/jquery.min.js.map
  - node_modules/popper.js/dist/umd/popper.min.js
  - node_modules/popper.js/dist/umd/popper.min.js.map
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map
  - node_modules/lazyload/lazyload.min.js
  - node_modules/bs-custom-file-input/dist/bs-custom-file-input.min.js
  - node_modules/bs-custom-file-input/dist/bs-custom-file-input.min.js.map
kramdown:
  auto_ids: true
  parse_block_html: true
plugins:
  - jekyll-sitemap
  # - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-autoprefixer
autoprefixer:
  only_production: true

# jekyll-seo-tag properties
twitter:
  username: filmhubhq
facebook:
  app_id: 159020761463817
  publisher: https://www.facebook.com/filmhubhq
  admins: 1034572123
logo: /images/icon_v2_600.png
social:
  name: Filmhub
  links:
    - https://blog.filmhub.com
    - https://twitter.com/filmhubhq
    - https://facebook.com/filmhubhq
    - https://www.youtube.com/user/kinonationfilms
    - https://www.linkedin.com/company/filmhub/
    - https://instagram.com/filmhubhq
author:
  twitter: filmhubhq
phone:

defaults:
  -
    scope:
      path: oldblog
    values:
      sitemap: false
  -
    scope:
      path: modals
    values:
      sitemap: false
  -
    scope:
      path: help
    values:
      sitemap: false

# Image resize service
# Assumes image id and minimagick geometry parameter to be appended as URL parameters,
# like https://d3fu66dsue3x22.cloudfront.net/images/:id/800x450%23
image_cdn: https://d3fu66dsue3x22.cloudfront.net/images
